<a href="https://colab.research.google.com/github/Arpan-000/PlayingWithPythonModule/blob/main/PlayingWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this Notebook,We'll familiarise ourselves with matrix manipulation using Numpy module of Python.

Vector: It's the coordinates  in the N dimensional space.



In [50]:
import numpy as np
Arr1 = np.array([3,1,2])
Arr2 = np.array([3,6,5])

In [51]:
#add of 1D vector
print(np.add(Arr1,Arr2))
#sub of 1D vector
print(np.subtract(Arr1,Arr2))
#dot product of vector
print(np.dot(Arr1,Arr2))
#length o f vector
print(np.linalg. norm(Arr1))
#type of vector
print(type(Arr1))


[6 7 7]
[ 0 -5 -3]
25
3.7416573867739413
<class 'numpy.ndarray'>


In [52]:
# shape of arr
Arr1.shape
#data type of each element
Arr1.dtype
# print specific element
Arr1[1,]
# slicing
y = Arr1[0:]  # 0: indicate from beginning  to end
y



array([3, 1, 2])

In [113]:
# argmax returns max  argument indices along certain axis
print("prints the mmax of array indices",end =" \t")
print(Arr1.argmax(0))
print("\n")


print("partition the  array indices",end =" \t\t")
print(Arr1.argpartition(0))
print("\n")

print("prints the min of array indices",end =" \t\t")
print(Arr1.argmin(0))
print("\n")

print("print the sorted list of array indices",end ="\t ")
print(Arr1.argsort(0))
print("\n")

Z = Arr2.copy()
print("print the Z array",end =" \t\t\t")
print(Z)
print("\n")

print("Cummulative Product",end ="\t\t\t")
print(Arr1.cumprod(0))
print("\n")

#print(Arr1.diagonal(1))
print("Max value",end ="\t\t\t\t\t")
print(Arr1.max(0))
print("\n")

print("Min value",end ="\t\t\t\t\t")
print(Arr1.min(0))
print("\n")

print("Mean value",end ="\t\t\t\t\t")
print(Arr1.mean(0))
print("\n")

print("variance value",end ="\t\t\t\t\t")
print(Arr1.var(0))
print("\n")


print("Standard deviation ",end="\t\t\t")
print(Arr1.std(0))
print("\n")

print("Returns non zero indices",end ="\t\t")
print(Arr1.nonzero())
print('\n')

# partition is used to divide in such a way that all number smaller than k is before k   but the order is not guaranteed
print("Partition array w.r.t 2",end="\t\t\t")
print(Arr1)
print("\n")

print("partition return  None since Partition doesn't return the array is just rearranges the array ")
print(Arr1.partition(2,axis = 0) )

#np.trace to sum the diagonal
#np.transpose

prints the mmax of array indices 	2


partition the  array indices 		[0 1 2]


prints the min of array indices 		0


print the sorted list of array indices	 [0 1 2]


print the Z array 			[3 6 5]


Cummulative Product			[1 2 6]


Max value					3


Min value					1


Mean value					2.0


variance value					0.6666666666666666


Standard deviation 			0.816496580927726


Returns non zero indices		(array([0, 1, 2]),)


Partition array w.r.t 2			[1 2 3]


partition return  None since Partition doesn't return the array is just rearranges the array 
None


In [118]:
Arr1.all()

True